Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2022-05, with the labels that each got.

#979 Release notes for 1.3.2
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.2.0.md
Labels: backport 1.3

#961 [Backport to 2.0] Fix 'openserach' typo in constants.tsx (#953)
  public/apps/configuration/constants.tsx
Labels: v2.0.0-GeneralAvailability

#989 Fixes broken main build which was caused due to version mismatch
  .github/workflows/integration-test.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.0

#996 Create release notes 2.0.0
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.0.0.0.md
Labels: backport 2.0
