Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2022-08, with the labels that each got.

#1032 Increment version to 2.2.0.0
  .github/workflows/integration-test.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#1060 Update release notes for 2.2.0.0 release
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.2.0.0.md
Labels: backport 2.x, backport 2.2

#1068 Increment version to 2.3.0.0
  .github/workflows/integration-test.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#1078 Adding release note 1.3.5
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.5.0.md
Labels: backport 1.3, backport 1.x
