Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2022-11, with the labels that each got.

#1167 [Backport 2.x] Support CI for Windows and MacOS (#1164)
  .github/actions/install-dashboards/action.yml
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
Labels: v2.4.0

#1184 Move tenant-related utils to common folder
  common/index.ts
  public/apps/configuration/utils/tenant-utils.tsx
  public/apps/configuration/utils/test/tenant-utils.test.tsx
  server/auth/types/authentication_type.ts
  server/multitenancy/tenant_resolver.ts
  server/saved_objects/saved_objects_wrapper.ts
Labels: v2.4.0

#1182 configure new ML plugin actions
  public/apps/configuration/constants.tsx
Labels: backport 2.x, v2.4.0, backport 2.4

#1197 Add release notes for 2.4.0.0
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#1202 Disable UTs for Windows while stablizing it
  .github/workflows/unit-test.yml
Labels: backport 2.x

#1201 Wait for tenant radio to be selected in flaky SAML integ test
  test/jest_integration/saml_auth.test.ts
Labels: backport 2.x

#1229 Add Firefox driver to the integration test workflow
  .github/workflows/integration-test.yml
Labels: backport 2.x
