Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2022-10, with the labels that each got.

#1114 Release notes 1.3.6
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.6.0.md
Labels: backport 1.3

#1112 Fix the UI user flow of selecting custom teanant on tenant switch panel
  public/apps/account/tenant-switch-panel.tsx
  public/apps/account/test/__snapshots__/tenant-switch-panel.test.tsx.snap
Labels: backport 2.x

#1121 Move to OpenSearch 3.0.0
  .github/workflows/integration-test.yml
  .github/workflows/prerequisite-test.yml
  opensearch_dashboards.json
  package.json
Labels: v3.0.0

#1164 Support CI for Windows and MacOS
  .github/actions/install-dashboards/action.yml
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
Labels: backport 2.x, v2.4.0

#1151 Remove multi-tenant path check in auth handler
  server/auth/types/authentication_type.test.ts
  server/auth/types/authentication_type.ts
  server/multitenancy/tenant_resolver.ts
Labels: backport 2.x, v2.4.0

#1110 Initial commit for multiple authentication
  common/index.ts
  public/apps/account/account-app.tsx
  public/apps/account/account-nav-button.tsx
  public/apps/account/log-out-button.tsx
  public/apps/account/test/__snapshots__/log-out-button.test.tsx.snap
  public/apps/account/test/account-app.test.tsx
  public/apps/account/test/account-nav-button.test.tsx
  public/apps/account/test/log-out-button.test.tsx
  public/apps/account/utils.tsx
  public/apps/login/login-app.tsx
  public/apps/login/login-page.tsx
  public/apps/login/test/__snapshots__/login-page.test.tsx.snap
  public/apps/login/test/login-page.test.tsx
  public/plugin.ts
  public/types.ts
  public/utils/logout-utils.tsx
  server/auth/auth_handler_factory.test.ts
  server/auth/auth_handler_factory.ts
  server/auth/types/authentication_type.ts
  server/auth/types/basic/basic_auth.ts
  server/auth/types/basic/routes.ts
  server/auth/types/index.ts
  server/auth/types/jwt/jwt_auth.test.ts
  server/auth/types/jwt/jwt_auth.ts
  server/auth/types/multiple/multi_auth.ts
  server/auth/types/multiple/routes.ts
  server/auth/types/openid/openid_auth.ts
  server/auth/types/openid/routes.ts
  server/auth/types/proxy/proxy_auth.ts
  server/auth/types/saml/routes.ts
  server/auth/types/saml/saml_auth.ts
  server/backend/opensearch_security_client.ts
  server/index.ts
  server/plugin.ts
Labels: backport 2.x, v2.4.0
