Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2022-04, with the labels that each got.

#928 Bumps version of main to 2.0.0.0
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  .stylelintrc.yml
  common/index.ts
  opensearch_dashboards.json
  package.json
  public/apps/account/test/__snapshots__/account-nav-button.test.tsx.snap
  public/apps/configuration/_index.scss
  public/apps/configuration/panels/audit-logging/_index.scss
  public/apps/configuration/panels/permission-tree/_index.scss
  public/apps/configuration/panels/tenant-list/test/__snapshots__/edit-modal.test.tsx.snap
  public/apps/configuration/panels/test/__snapshots__/nav-panel.test.tsx.snap
  public/apps/customerror/_index.scss
  public/apps/login/_index.scss
  public/index.scss
  public/index.ts
  server/auth/types/basic/routes.ts
Labels: v2.0.0

#941 [Build] bump to 2.0.0.0-rc1
  opensearch_dashboards.json
  package.json
Labels: v2.0.0

#940 Fix broken `nextUrl=` parameter logic
  .github/workflows/integration-test.yml
  server/auth/types/basic/basic_auth.ts
  server/auth/types/basic/routes.ts
  server/auth/types/jwt/jwt_auth.ts
  server/auth/types/openid/openid_auth.ts
  server/multitenancy/tenant_resolver.ts
  server/utils/next_url.test.ts
  server/utils/next_url.ts
  test/jest_integration/basic_auth.test.ts
Labels: bug, v2.0.0

#968 Enforce authentication on api/status route by default
  server/index.ts
  test/jest_integration/basic_auth.test.ts
Labels: backport 2.0
