Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2023-08, with the labels that each got.

#1533 [2.x] Change the regex command in install dashboard GHA + Increment version to 2.10.0
  .github/actions/install-dashboards/action.yml
  opensearch_dashboards.json
  package.json
Labels: v2.10.0

#1543 Add release notes for 1.3.12.0
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.12.0.md
Labels: backport 1.3, backport 1.x

#1538 Make the steps diagram honor the theme
  public/apps/configuration/_index.scss
  public/apps/configuration/panels/get-started.tsx
  public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
  public/assets/get_started.svg
  public/assets/get_started_layer_1.svg
  public/assets/get_started_layer_2.svg
Labels: backport 2.x
