Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2023-10, with the labels that each got.

#1596 CI fixes for adapting admin password change and fix the Cypress browser
  .github/workflows/cypress-test-tenancy-disabled.yml
  .github/workflows/cypress-test.yml
  .github/workflows/integration-test.yml
Labels: backport 2.x

#1580 Fix OIDC refresh token flow when using the cookie splitter
  server/session/cookie_splitter.test.ts
  server/session/cookie_splitter.ts
Labels: backport 2.x, v2.11.0

#1600 Adds 2.11.0.0 release notes
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#1626 Add permissions for async query and patch datasource API
  public/apps/configuration/constants.tsx
Labels: backport 2.x, backport 2.11
