Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2023-01, with the labels that each got.

#1290 Add Notifications cluster permissions
  public/apps/configuration/constants.tsx
Labels: backport 2.x

#1292 Fix regression in jwt url parameter by awaiting async getAdditionalAuthHeader
  package.json
  server/auth/types/authentication_type.ts
  server/auth/types/jwt/jwt_helper.test.ts
  server/auth/types/multiple/multi_auth.ts
  test/jest.config.server.js
  test/jest_integration/jwt_auth.test.ts
  test/setup/after_env.js
Labels: backport 2.x, backport 2.4, backport 2.5

#1297 Add release note for 2.5.0
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5
