Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2023-03, with the labels that each got.

#1359 Replace legacy template with index template
  server/multitenancy/tenant_index.ts
  server/multitenancy/test/tenant_index.test.ts
Labels: backport 1.3, backport 2.0, backport 2.x, backport 1.x, backport 1.2, backport 2.1, backport 1.0, backport 1.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport opendistro-1.13, backport opendistro-1.11

#1358 added loginEndPointWithPath
  public/apps/login/login-page.tsx
  public/apps/login/test/__snapshots__/login-page.test.tsx.snap
Labels: backport 2.x

#1379 Add release notes for 1.3.9
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.9.0.md
Labels: backport 1.3
