Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2024-02, with the labels that each got.

#1744 Fixes Short URL redirection for SAML login
  server/auth/types/saml/saml_auth.ts
  server/multitenancy/tenant_resolver.ts
  test/cypress/e2e/saml/saml_auth_test.spec.js
  test/cypress/support/commands.js
  test/cypress/support/constants.js
  test/cypress/support/index.d.ts
Labels: v2.12.0

#1772 Add release notes for 2.12.0.0
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#1780 Clear the contents of opensearch_dashboards prior to putting settings
  .github/workflows/cypress-test-tenancy-disabled.yml
  .github/workflows/cypress-test.yml
Labels: backport 2.x

#1787 Add loose flag to OSD bootstrap
  .github/actions/install-dashboards/action.yml
  .github/workflows/verify-binary-installation.yml
Labels: backport 2.x

#1773 Fix cookie expiry issues from IDP/JWT auth methods, disables keepalive for JWT/IDP
  server/auth/types/authentication_type.test.ts
  server/auth/types/authentication_type.ts
  server/auth/types/basic/basic_auth.test.ts
  server/auth/types/basic/basic_auth.ts
  server/auth/types/jwt/jwt_auth.ts
  server/auth/types/jwt/jwt_helper.test.ts
  server/auth/types/jwt/jwt_helper.ts
  server/auth/types/multiple/multi_auth.test.ts
  server/auth/types/multiple/multi_auth.ts
  server/auth/types/openid/openid_auth.test.ts
  server/auth/types/openid/openid_auth.ts
  server/auth/types/openid/routes.ts
  server/auth/types/proxy/proxy_auth.test.ts
  server/auth/types/proxy/proxy_auth.ts
  server/auth/types/saml/saml_auth.test.ts
  server/auth/types/saml/saml_auth.ts
Labels: backport 2.x
