Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2024-07, with the labels that each got.

#2033 Remove dependency on opensearch build repo libs from custom build.sh
  scripts/build.sh
Labels: bug, release, backport 2.x, v2.16.0

#2039 Addresses CVE-2024-4068 and updates yarn.lock
  package.json
  yarn.lock
Labels: backport 2.x

#2024 feat: http proxy support for oidc
  package.json
  server/auth/types/openid/openid_auth.ts
  yarn.lock
Labels: backport 2.x

#2022 Conform to Navigation changes from OSD core
  public/apps/configuration/app-router.tsx
  public/apps/configuration/configuration-app.tsx
  public/apps/configuration/panels/tenant-list/configure_tab1.tsx
  public/apps/configuration/panels/tenant-list/manage_tab.tsx
  public/apps/configuration/panels/tenant-list/tenant-list.tsx
  public/apps/configuration/panels/tenant-list/test/tenant-list.test.tsx
  public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap
  public/apps/configuration/test/app-router.test.tsx
  public/apps/configuration/top-nav-menu.tsx
  public/apps/types.ts
  public/plugin.ts
  public/utils/datasource-utils.ts
Labels: backport 2.x

#2048 Update nextUrl validation to incorporate serverBasePath
  server/auth/types/basic/routes.ts
  server/auth/types/openid/routes.ts
  server/auth/types/proxy/routes.ts
  server/auth/types/saml/routes.ts
  server/utils/next_url.test.ts
  server/utils/next_url.ts
Labels: backport 2.x, backport 2.16

#2051 [MDS] Adds datasource filter for version decoupling
  opensearch_dashboards.json
  package.json
  public/apps/configuration/top-nav-menu.tsx
  public/utils/datasource-utils.ts
  public/utils/test/datasource-utils.test.ts
  test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
  yarn.lock
Labels: backport 2.x, v2.16.0, backport 2.16

#2053 [Backport 2.16] [MDS] Adds datasource filter for version decoupling (#2051)
  opensearch_dashboards.json
  package.json
  public/apps/configuration/top-nav-menu.tsx
  public/utils/datasource-utils.ts
  public/utils/test/datasource-utils.test.ts
  test/cypress/e2e/multi-datasources/multi_datasources_enabled.spec.js
Labels: v2.16.0

#2047 Add retry to bootstrap for windows related workflows
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
Labels: backport 2.x

#2061 Adds 2.16 release notes
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#2057 Do not register tenancy app if disabled in yml
  common/index.ts
  public/plugin.ts
  public/test/plugin.test.ts
Labels: backport 2.x

#2074 Updates backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x
