Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2024-04, with the labels that each got.

#1865 Remove date from release notes
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.13.0.0.md
Labels: backport 2.x, backport 2.13

#1872 Clear session storage on auto-logout & remove unused saml function
  public/apps/account/test/plugin.test.tsx
  public/apps/account/utils.tsx
  public/utils/logout-utils.tsx
Labels: backport 2.x

#1881 Update copy for tenancy tab
  public/apps/configuration/panels/tenant-list/configure_tab1.tsx
  public/apps/configuration/panels/tenant-list/manage_tab.tsx
  public/apps/configuration/panels/tenant-list/tenant-list.tsx
  public/apps/configuration/panels/tenant-list/test/__snapshots__/tenant-list.test.tsx.snap
Labels: backport 2.x

#1839 Fixes saml login flow to work with anonymous auth
  common/index.ts
  public/apps/login/login-page.tsx
  public/apps/login/test/__snapshots__/login-page.test.tsx.snap
  public/apps/login/test/login-page.test.tsx
  server/auth/types/basic/basic_auth.ts
  server/auth/types/multiple/multi_auth.ts
  server/auth/types/saml/routes.ts
  server/backend/opensearch_security_client.ts
  test/constant.ts
  test/jest_integration/basic_auth.test.ts
Labels: backport 2.x

#1895 Adds 1.3.16 release notes
  release-notes/opensearch-security-dashboards-plugin.release-notes-1.3.16.0.md
Labels: v1.3.16

#1902 Bump jose from 4.11.2 to 5.2.4
  package.json
  yarn.lock
Labels: backport 2.x

#1908 Adds flow-framework transport actions to the static dropdown list of cluster permissions
  public/apps/configuration/constants.tsx
Labels: backport 2.x

#1916 Add fix for data source disabled plugin should work
  .github/workflows/unit-test.yml
  public/apps/configuration/app-router.tsx
  public/apps/configuration/test/__snapshots__/app-router.test.tsx.snap
  public/apps/configuration/test/app-router.test.tsx
  public/utils/datasource-utils.ts
  public/utils/test/datasource-utils.test.ts
  test/cypress/e2e/multi-datasources/multi_datasources_disabled.spec.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1923 Fix oidc cypress test and remove doc link
  server/auth/types/authentication_type.ts
  test/cypress/e2e/oidc/oidc_auth_test.spec.js
Labels: backport 2.x

#1762 Create a password strength UI for security dashboards plugin
  package.json
  public/apps/account/password-reset-panel.tsx
  public/apps/configuration/utils/password-edit-panel.tsx
  public/apps/configuration/utils/password-strength-bar.tsx
  public/apps/configuration/utils/test/__snapshots__/password-strength-bar.test.tsx.snap
  public/apps/configuration/utils/test/password-strength-bar.test.tsx
  yarn.lock
Labels: backport 2.x, backport 2.14
