Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2024-09, with the labels that each got.

#2111 Adds release notes for 2.17
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#2121 [Look&Feel]update category label
  public/plugin.ts
Labels: backport 2.x

#2126 [Backport 2.17] Add the release note for 2.17.1
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.0.0.md
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.17.1.0.md
Labels: backport 2.x, backport main
