Repository opensearch-project/security-dashboards-plugin, pull requests merged in 2024-10, with the labels that each got.

#2130 Fix button label
  .github/actions/run-cypress-tests/action.yml
  public/apps/configuration/panels/get-started.tsx
  public/apps/configuration/panels/test/__snapshots__/get-started.test.tsx.snap
Labels: backport 2.x, v2.18.0

#2107 Add JWT authentication type to MultipleAuthentication
  public/apps/login/login-page.tsx
  server/auth/types/authentication_type.ts
  server/auth/types/multiple/multi_auth.ts
  test/constant.ts
  test/jest_integration/jwt_multiauth.test.ts
Labels: backport 2.x, v2.18.0

#2134 Move Stephen to Emeritus maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.3, backport 2.x

#2137 Add release notes for 2.18 release
  release-notes/opensearch-security-dashboards-plugin.release-notes-2.18.0.0.md
Labels: backport 2.x

#2141 Bump express for CVE
  package.json
  yarn.lock
Labels: backport 2.x, backport main
